import { createHash } from "node:crypto";
import type { ChangeEvent, DiagnosisInput, LearningDiagnostic, LearningService, LearningStage, LessonCandidate, LockSnapshot, MeasurementInput, PlayerMeasurement, PreLockDecision, PreLockInput } from "@sports-engine/contracts";

export class DeterministicLearningService implements LearningService {
  preLock(input: PreLockInput): PreLockDecision {
    if (!input.changeEvents.length) return { decision: "KEEP", requiresUserConfirmation: false, immutableLineupIds: input.enteredLineups.map((lineup) => lineup.id), affectedStages: [], rationale: "No material pre-lock changes were detected." };
    const highest = input.changeEvents.reduce((current, event) => severity(event.materiality) > severity(current.materiality) ? event : current, input.changeEvents[0]);
    const decision = highest.materiality === "CRITICAL" ? "REBUILD" : highest.materiality === "HIGH" ? "ADJUST" : "KEEP";
    const immutable = input.enteredLineups.map((lineup) => lineup.id);
    return { decision, requiresUserConfirmation: immutable.length > 0 && decision !== "KEEP", immutableLineupIds: immutable, affectedStages: stagesFor(highest), rationale: immutable.length && decision !== "KEEP" ? `${highest.eventType} is ${highest.materiality}, but entered lineups remain immutable. Explicit user confirmation is required before any replacement or adjustment.` : `${highest.eventType} is ${highest.materiality}; the earliest affected stages are ${stagesFor(highest).join(", ") || "not yet determined"}.` };
  }
  createLockSnapshot(snapshot: Omit<LockSnapshot, "id">): LockSnapshot { return { ...snapshot, id: createHash("sha256").update(`${snapshot.tenantId}:${snapshot.generatedLineupId}:${snapshot.lockedAt}`).digest("hex").slice(0, 32) }; }
  measure(input: MeasurementInput): MeasurementInput { return { ...input, measurements: input.measurements.map((measurement) => { const actual = measurement.actualDk; const error = actual !== undefined && measurement.projectedMedian !== undefined ? actual - measurement.projectedMedian : measurement.projectionError; const within = actual !== undefined && measurement.projectedFloor !== undefined && measurement.projectedCeiling !== undefined ? actual >= measurement.projectedFloor && actual <= measurement.projectedCeiling : measurement.withinExpectedRange; return { ...measurement, projectionError: error, withinExpectedRange: within }; }) }; }
  diagnose(input: DiagnosisInput, now = new Date()): { diagnostic: LearningDiagnostic; lesson?: LessonCandidate } {
    const opportunityError = input.measurements.find(hasMaterialOpportunityError); const outOfRange = input.measurements.filter((measurement) => measurement.withinExpectedRange === false); let errorStage: LearningStage = "VARIANCE"; let diagnosis = "Observed outcome was evaluated against the projected distribution; losing alone is not evidence of model failure."; let confidence: LearningDiagnostic["confidence"] = "MEDIUM";
    if (opportunityError) { errorStage = "PROJECTION"; diagnosis = "Actual opportunity materially differed from the explicit opportunity assumption used by projection."; confidence = "HIGH"; } else if (input.selectedVsOptimizer && input.selectedVsOptimizer.bestAlternativeMedian > input.selectedVsOptimizer.selectedMedian * 1.1) { errorStage = "SELECTION"; diagnosis = "A materially stronger optimizer alternative existed relative to the selected lineup's median; selection should be reviewed against contest context."; confidence = "MEDIUM"; } else if (outOfRange.length && outOfRange.length === input.measurements.length) { diagnosis = "All measured player outcomes fell outside the projected ranges; the result is notable, but requires repeated samples before changing rules."; confidence = "LOW"; }
    const diagnostic: LearningDiagnostic = { id: createHash("sha256").update(`${input.tenantId}:${input.generationRunId}:${input.result.id}`).digest("hex").slice(0, 32), tenantId: input.tenantId, generationRunId: input.generationRunId, subjectType: "GENERATED_LINEUP", subjectId: input.result.generatedLineupId, errorStage, severity: errorStage === "VARIANCE" ? "LOW" : "MEDIUM", confidence, assumption: opportunityError ? JSON.stringify(opportunityError.projectedOpportunity) : "Projected distribution and selected optimizer candidate.", actualOutcome: input.result.actualDkPoints === undefined ? undefined : `Actual DraftKings points: ${input.result.actualDkPoints}.`, evidence: { measurementCount: input.measurements.length, outOfRangeCount: outOfRange.length, result: input.result, selectedVsOptimizer: input.selectedVsOptimizer }, diagnosis };
    const lesson = input.generalizable ? { id: `${diagnostic.id}:lesson`, tenantId: input.tenantId, sport: input.sport, stage: errorStage, observation: diagnosis, proposedChange: errorStage === "VARIANCE" ? "Continue accumulating samples; do not change rules from one result." : `Review ${errorStage} assumptions against repeated measured outcomes.`, status: "OBSERVED" as const, sampleCount: 1, confidence, evidence: [diagnostic.evidence] } : undefined;
    return { diagnostic, lesson };
  }
}
function severity(value: ChangeEvent["materiality"]): number { return { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 }[value]; }
function stagesFor(event: ChangeEvent): LearningStage[] { if (/injur|availab|lineup|role/i.test(event.eventType)) return ["RESEARCH", "SPORT_ADJUSTMENT", "PROJECTION", "OPTIMIZE", "SELECTION"]; if (/projection|model/i.test(event.eventType)) return ["PROJECTION", "OPTIMIZE", "SELECTION"]; if (/contest|ownership|duplication/i.test(event.eventType)) return ["OPTIMIZE", "SELECTION"]; return ["RESEARCH"]; }
function hasMaterialOpportunityError(measurement: PlayerMeasurement): boolean { if (!measurement.projectedOpportunity || !measurement.actualOpportunity) return false; return Object.keys(measurement.projectedOpportunity).some((key) => { const projected = measurement.projectedOpportunity?.[key]; const actual = measurement.actualOpportunity?.[key]; return projected !== undefined && actual !== undefined && Math.abs(actual - projected) > Math.max(1, Math.abs(projected) * 0.2); }); }
