import type { VercelRequest, VercelResponse } from '@vercel/node';
import { cors, method, parseBody, respondError, tenantContext } from '../../server/runtime.js';

export default async function handler(req: VercelRequest, res: VercelResponse): Promise<void> {
  if (!method(req, res, ['POST'])) return;
  try {
    const context = await tenantContext(); const body = parseBody(req); const image = String(body.imageDataUrl ?? '');
    if (!image.startsWith('data:image/')) throw new Error('imageDataUrl must be a data:image/* URL.');
    const assetId = crypto.randomUUID(); const path = `${context.tenantId}/draftkings/${context.userId}/${assetId}.png`; const comma = image.indexOf(','); const encoded = comma >= 0 ? image.slice(comma + 1) : image; const uploaded = await context.db.storage.from('draftkings').upload(path, Buffer.from(encoded, 'base64'), { contentType: image.slice(5, image.indexOf(';')), upsert: false }); if (uploaded.error) throw uploaded.error;
    const apiKey = process.env.OPENAI_API_KEY?.trim(); if (!apiKey) throw new Error('OPENAI_API_KEY is required for screenshot ingestion.');
    const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { authorization: `Bearer ${apiKey}`, 'content-type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? 'gpt-5', store: false, input: [{ role: 'user', content: [{ type: 'input_text', text: 'Extract only DraftKings contest/slate facts from this screenshot. Do not infer missing values. Return null or empty arrays for unreadable fields.' }, { type: 'input_image', image_url: image }] }], text: { format: { type: 'json_schema', name: 'draftkings_screenshot', strict: true, schema: { type: 'object', additionalProperties: false, properties: { sport: { type: ['string', 'null'] }, contestName: { type: ['string', 'null'] }, contestFormat: { type: ['string', 'null'] }, lockTime: { type: ['string', 'null'] }, salaryCap: { type: ['number', 'null'] }, scoringRules: { type: 'object', additionalProperties: { type: 'number' } }, players: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { playerId: { type: ['string', 'null'] }, playerName: { type: 'string' }, team: { type: ['string', 'null'] }, salary: { type: ['number', 'null'] }, captainSalary: { type: ['number', 'null'] }, utilitySalary: { type: ['number', 'null'] }, eligibility: { type: 'array', items: { type: 'string' } } }, required: ['playerId', 'playerName', 'team', 'salary', 'captainSalary', 'utilitySalary', 'eligibility'] } } }, required: ['sport', 'contestName', 'contestFormat', 'lockTime', 'salaryCap', 'scoringRules', 'players'] } } } }) }); if (!response.ok) throw new Error(`OpenAI screenshot extraction returned HTTP ${response.status}.`); const payload = await response.json() as Record<string, unknown>; const extracted = typeof payload.output_text === 'string' ? JSON.parse(payload.output_text) : {}; cors(req, res); res.status(201).json({ assetId, path, extracted, source: 'DRAFTKINGS_SCREENSHOT', status: 'EXTRACTED' });
  } catch (error) { respondError(req, res, error); }
}
