export interface CalibrationRow { predicted: number; actual: number; p20?: number; p50?: number; p90?: number; selected?: boolean; alternative?: number; cashPredicted?: number; cashed?: boolean; payout?: number; entryFee?: number; }

export function brierScore(rows: CalibrationRow[]): number | null { const usable = rows.filter((r) => Number.isFinite(r.cashPredicted) && typeof r.cashed === 'boolean'); return usable.length ? usable.reduce((s, r) => s + (r.cashPredicted! - (r.cashed ? 1 : 0)) ** 2, 0) / usable.length : null; }
export function logLoss(rows: CalibrationRow[]): number | null { const usable = rows.filter((r) => Number.isFinite(r.cashPredicted) && typeof r.cashed === 'boolean'); return usable.length ? usable.reduce((s, r) => { const p = Math.min(1 - 1e-6, Math.max(1e-6, r.cashPredicted!)); return s - ((r.cashed ? 1 : 0) * Math.log(p) + (r.cashed ? 0 : 1) * Math.log(1 - p)); }, 0) / usable.length : null; }
/** Empirical quantile coverage: share of actual outcomes at or below the predicted q_tau. */
export function quantileCoverage(rows: CalibrationRow[], quantile: 'p20' | 'p50' | 'p90'): number | null { const usable = rows.filter((r) => Number.isFinite(r.actual) && Number.isFinite(r[quantile])); return usable.length ? usable.filter((r) => r.actual <= r[quantile]!).length / usable.length : null; }
export function rankCorrelation(rows: CalibrationRow[]): number | null { const usable = rows.filter((r) => Number.isFinite(r.predicted) && Number.isFinite(r.actual)); if (usable.length < 2) return null; const a = rank(usable.map((r) => r.predicted)); const b = rank(usable.map((r) => r.actual)); const meanA = a.reduce((s, x) => s + x, 0) / a.length; const meanB = b.reduce((s, x) => s + x, 0) / b.length; const numerator = a.reduce((s, x, i) => s + (x - meanA) * (b[i] - meanB), 0); const denominator = Math.sqrt(a.reduce((s, x) => s + (x - meanA) ** 2, 0) * b.reduce((s, x) => s + (x - meanB) ** 2, 0)); return denominator ? numerator / denominator : 0; }
export function regret(rows: CalibrationRow[]): number | null { const usable = rows.filter((r) => Number.isFinite(r.actual) && Number.isFinite(r.alternative)); return usable.length ? usable.reduce((s, r) => s + (r.alternative! - r.actual), 0) / usable.length : null; }
export function roi(rows: CalibrationRow[]): number | null { const usable = rows.filter((r) => Number.isFinite(r.payout) && Number.isFinite(r.entryFee) && r.entryFee! > 0); return usable.length ? usable.reduce((s, r) => s + (r.payout! - r.entryFee!), 0) / usable.reduce((s, r) => s + r.entryFee!, 0) : null; }
function rank(values: number[]): number[] { const sorted = values.map((value, index) => ({ value, index })).sort((a, b) => b.value - a.value); const ranks = Array(values.length).fill(0) as number[]; for (let start = 0; start < sorted.length;) { let end = start + 1; while (end < sorted.length && sorted[end].value === sorted[start].value) end += 1; const averageRank = ((start + 1) + end) / 2; for (let index = start; index < end; index += 1) ranks[sorted[index].index] = averageRank; start = end; } return ranks; }
