import type { SupabaseClient } from "@supabase/supabase-js";
import type { ChangeEvent, ContestResult, LearningDiagnostic, LessonCandidate, LockSnapshot, PlayerMeasurement, WatchItemRecord } from "@sports-engine/contracts";

export interface LearningRepository { saveWatchItem(item: Omit<WatchItemRecord, "id">): Promise<void>; saveChangeEvent(event: Omit<ChangeEvent, "id">): Promise<void>; saveLockSnapshot(snapshot: LockSnapshot): Promise<void>; saveContestResult(result: ContestResult): Promise<void>; saveMeasurements(measurements: PlayerMeasurement[]): Promise<void>; saveDiagnostic(diagnostic: LearningDiagnostic): Promise<void>; saveLesson(lesson: LessonCandidate): Promise<void>; }
export class SupabaseLearningRepository implements LearningRepository {
  constructor(private readonly client: SupabaseClient) {}
  async saveWatchItem(item: Omit<WatchItemRecord, "id">): Promise<void> { const { error } = await this.client.from("floyd_dfs_watch_items").insert({ ...item, tenant_id: item.tenantId, generation_run_id: item.generationRunId, current_state: item.currentState ?? null, expected_update_at: item.expectedUpdateAt ?? null }); if (error) throw error; }
  async saveChangeEvent(event: Omit<ChangeEvent, "id">): Promise<void> { const { error } = await this.client.from("floyd_dfs_change_events").insert({ ...event, tenant_id: event.tenantId, generation_run_id: event.generationRunId, event_type: event.eventType, previous_state: event.previousState ?? null, new_state: event.newState ?? null, affected_lineup_ids: event.affectedLineupIds ?? [] }); if (error) throw error; }
  async saveLockSnapshot(snapshot: LockSnapshot): Promise<void> { const { error } = await this.client.from("floyd_dfs_lock_snapshots").insert({ id: snapshot.id, tenant_id: snapshot.tenantId, generated_lineup_id: snapshot.generatedLineupId, locked_at: snapshot.lockedAt, lineup_payload: snapshot.lineupPayload, projection_snapshot: snapshot.projectionSnapshot, game_script: snapshot.gameScript ?? null, risk_flags: snapshot.riskFlags, research_version: snapshot.researchVersion, adjustment_version: snapshot.adjustmentVersion, projection_version: snapshot.projectionVersion, optimization_version: snapshot.optimizationVersion, selection_version: snapshot.selectionVersion }); if (error) throw error; }
  async saveContestResult(result: ContestResult): Promise<void> { const { error } = await this.client.from("floyd_dfs_contest_results").insert({ id: result.id, tenant_id: result.tenantId, generated_lineup_id: result.generatedLineupId, actual_dk_points: result.actualDkPoints ?? null, finish_position: result.finishPosition ?? null, finish_percentile: result.finishPercentile ?? null, payout: result.payout ?? null, roi: result.roi ?? null, result_payload: result.resultPayload ?? null, measured_at: result.measuredAt }); if (error) throw error; }
  async saveMeasurements(measurements: PlayerMeasurement[]): Promise<void> { if (!measurements.length) return; const { error } = await this.client.from("floyd_dfs_player_measurements").insert(measurements.map((measurement) => ({ id: measurement.id, tenant_id: measurement.tenantId, generated_lineup_id: measurement.generatedLineupId, player_id: measurement.playerId, projected_opportunity: measurement.projectedOpportunity ?? null, actual_opportunity: measurement.actualOpportunity ?? null, projected_floor: measurement.projectedFloor ?? null, projected_median: measurement.projectedMedian ?? null, projected_ceiling: measurement.projectedCeiling ?? null, actual_dk: measurement.actualDk ?? null, projection_error: measurement.projectionError ?? null, within_expected_range: measurement.withinExpectedRange ?? null }))); if (error) throw error; }
  async saveDiagnostic(diagnostic: LearningDiagnostic): Promise<void> { const { error } = await this.client.from("floyd_dfs_learning_diagnostics").insert({ id: diagnostic.id, tenant_id: diagnostic.tenantId, generation_run_id: diagnostic.generationRunId, subject_type: diagnostic.subjectType, subject_id: diagnostic.subjectId, error_stage: diagnostic.errorStage, severity: diagnostic.severity ?? null, confidence: diagnostic.confidence, assumption: diagnostic.assumption ?? null, actual_outcome: diagnostic.actualOutcome ?? null, evidence: diagnostic.evidence, diagnosis: diagnostic.diagnosis }); if (error) throw error; }
  async saveLesson(lesson: LessonCandidate): Promise<void> { const { error } = await this.client.from("floyd_dfs_lesson_candidates").insert({ id: lesson.id.replace(/:lesson$/, ""), tenant_id: lesson.tenantId, sport: lesson.sport, stage: lesson.stage, observation: lesson.observation, proposed_change: lesson.proposedChange ?? null, status: lesson.status, sample_count: lesson.sampleCount, confidence: lesson.confidence ?? null, evidence: lesson.evidence }); if (error) throw error; }
}
