import type { SupabaseClient } from "@supabase/supabase-js";
import type { OptimizerPackage, Sport } from "@sports-engine/contracts";

export interface OptimizationRunRecord { id: string; tenantId: string; generationRunId: string; version: number; objectiveProfile: OptimizerPackage["objectiveProfile"]; optimizerPackage: OptimizerPackage; status: OptimizerPackage["status"]; createdAt: string; }
export interface OptimizerRepository { save(run: Omit<OptimizationRunRecord, "id">): Promise<OptimizationRunRecord>; getLatest(generationRunId: string, tenantId: string): Promise<OptimizationRunRecord | undefined>; }

export class SupabaseOptimizerRepository implements OptimizerRepository {
  constructor(private readonly client: SupabaseClient) {}
  async save(run: Omit<OptimizationRunRecord, "id">): Promise<OptimizationRunRecord> { const { data, error } = await this.client.from("floyd_dfs_optimization_runs").insert({ tenant_id: run.tenantId, generation_run_id: run.generationRunId, version: run.version, objective_profile: run.objectiveProfile, optimizer_package: run.optimizerPackage, status: run.status, created_at: run.createdAt }).select("*").single(); if (error) throw error; const record = mapRun(data); const rows = run.optimizerPackage.candidates.map((candidate) => ({ tenant_id: run.tenantId, optimization_run_id: record.id, candidate_key: candidate.id, salary_used: candidate.salaryUsed, salary_remaining: candidate.salaryRemaining, floor: candidate.floor, median: candidate.median, ceiling: candidate.ceiling, correlation_score: candidate.correlationScore, optimal_lineup_frequency: candidate.optimalLineupFrequency, top_one_percent_frequency: candidate.topOnePercentFrequency, ownership_estimate: candidate.ownershipEstimate, leverage_score: candidate.leverageScore, duplication_risk: candidate.duplicationRisk, estimated_duplicates: candidate.estimatedDuplicates, median_rank: candidate.medianRank, ceiling_rank: candidate.ceilingRank, tournament_rank: candidate.tournamentRank, candidate_types: candidate.candidateTypes, roster_slots: candidate.rosterSlots, game_script_cluster: candidate.gameScriptCluster, strategic_similarity: candidate.strategicSimilarity, risk_flags: candidate.riskFlags })); if (rows.length) { const result = await this.client.from("floyd_dfs_lineup_candidates").insert(rows); if (result.error) throw result.error; } return record; }
  async getLatest(generationRunId: string, tenantId: string): Promise<OptimizationRunRecord | undefined> { const { data, error } = await this.client.from("floyd_dfs_optimization_runs").select("*").eq("generation_run_id", generationRunId).eq("tenant_id", tenantId).order("version", { ascending: false }).limit(1).maybeSingle(); if (error) throw error; return data ? mapRun(data) : undefined; }
}
function mapRun(row: Record<string, unknown>): OptimizationRunRecord { return { id: String(row.id), tenantId: String(row.tenant_id), generationRunId: String(row.generation_run_id), version: Number(row.version), objectiveProfile: row.objective_profile as OptimizationRunRecord["objectiveProfile"], optimizerPackage: row.optimizer_package as OptimizerPackage, status: row.status as OptimizerPackage["status"], createdAt: String(row.created_at) }; }
