import type { SupabaseClient } from "@supabase/supabase-js";
import type { ProjectionPackage, Sport } from "@sports-engine/contracts";

export interface ProjectionRunRecord { id: string; tenantId: string; generationRunId: string; version: number; sport: Sport; modelVersion: string; simulationRuns: number; projectionPackage: ProjectionPackage; status: ProjectionPackage["status"]; createdAt: string; }
export interface ProjectionRepository { save(run: Omit<ProjectionRunRecord, "id">): Promise<ProjectionRunRecord>; getLatest(generationRunId: string, tenantId: string): Promise<ProjectionRunRecord | undefined>; }

export class SupabaseProjectionRepository implements ProjectionRepository {
  constructor(private readonly client: SupabaseClient) {}
  async save(run: Omit<ProjectionRunRecord, "id">): Promise<ProjectionRunRecord> { const { data, error } = await this.client.from("floyd_dfs_projection_runs").insert({ tenant_id: run.tenantId, generation_run_id: run.generationRunId, version: run.version, sport: run.sport, model_version: run.modelVersion, simulation_runs: run.simulationRuns, projection_package: run.projectionPackage, status: run.status, created_at: run.createdAt }).select("*").single(); if (error) throw error; const record = mapRun(data); const rows = run.projectionPackage.players.map((player) => ({ tenant_id: run.tenantId, projection_run_id: record.id, player_id: player.playerId, baseline_opportunity: player.baselineOpportunity, adjusted_opportunity: player.adjustedOpportunity, opportunity_delta: player.opportunityDelta, component_projection: player.componentProjection, floor_p20: player.projectedOutcomes.floorP20, median_p50: player.projectedOutcomes.medianP50, ceiling_p90: player.projectedOutcomes.ceilingP90, median_per_1k: player.salaryEfficiency.medianPer1k, ceiling_per_1k: player.salaryEfficiency.ceilingPer1k, confidence: player.confidence, uncertainty_factors: player.uncertaintyFactors, watch_dependencies: player.watchDependencies, model_version: player.modelVersion })); if (rows.length) { const result = await this.client.from("floyd_dfs_player_projections").insert(rows); if (result.error) throw result.error; } return record; }
  async getLatest(generationRunId: string, tenantId: string): Promise<ProjectionRunRecord | undefined> { const { data, error } = await this.client.from("floyd_dfs_projection_runs").select("*").eq("generation_run_id", generationRunId).eq("tenant_id", tenantId).order("version", { ascending: false }).limit(1).maybeSingle(); if (error) throw error; return data ? mapRun(data) : undefined; }
}
function mapRun(row: Record<string, unknown>): ProjectionRunRecord { return { id: String(row.id), tenantId: String(row.tenant_id), generationRunId: String(row.generation_run_id), version: Number(row.version), sport: row.sport as Sport, modelVersion: String(row.model_version), simulationRuns: Number(row.simulation_runs), projectionPackage: row.projection_package as ProjectionPackage, status: row.status as ProjectionPackage["status"], createdAt: String(row.created_at) }; }
